/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.starterdemo;

import org.junit.Test;
import static org.junit.Assert.*;

public class UserApplicationTest {
    @Test public void appHasAGreeting() {
        UserApplication classUnderTest = new UserApplication();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
