defaultMessage: "Hello World"

dataSource:
  driverClass: org.postgresql.Driver
  user: summoner-service
  password: "dev_password"
  url: jdbc:postgresql://devDB:5432/simple_user_db
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
